# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'IRSMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking', '0.9.1'
pod 'Toaster'
pod 'SharkORM'
pod 'SlideMenuControllerSwift'
pod 'DatePickerDialog'
pod 'PureLayout', '~> 2.0.5'
pod 'DropDown'
# Pods for IRSMobile

end
