# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'IRSMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'AFNetworking', '0.9.1'
pod 'SlideMenuControllerSwift'
# Pods for IRSMobile

  target 'IRSMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IRSMobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
